"""Add Review Model

Revision ID: 95df72cfee8b
Revises: b896394dc7c3
Create Date: 2024-03-23 01:57:29.132907

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '95df72cfee8b'
down_revision = 'b896394dc7c3'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reviews',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('score', sa.Integer(), nullable=True),
    sa.Column('comment', sa.String(), nullable=True),
    sa.Column('game_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('reviews')
    # ### end Alembic commands ###
