"""Create Game Model

Revision ID: b896394dc7c3
Revises: f91f7b83b5df
Create Date: 2024-03-23 01:56:14.861774

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b896394dc7c3'
down_revision = 'f91f7b83b5df'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('reviews')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reviews',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('score', sa.INTEGER(), nullable=True),
    sa.Column('comment', sa.VARCHAR(), nullable=True),
    sa.Column('game_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], name='fk_reviews_game_id_games'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
