"""Add Review Model

Revision ID: f91f7b83b5df
Revises: 8b9d7e569324
Create Date: 2024-03-23 01:54:06.584621

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f91f7b83b5df'
down_revision = '8b9d7e569324'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
